version: '3.1'
services:
  db:
    container_name: mssql-tester
    image: mcr.microsoft.com/mssql/server:2022-latest
    restart: always
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: Password!
    ports:
      - 1433:1433
    volumes:
      - db-data:/var/opt/mssql
volumes:
  db-data: